all:
  hosts:
    cp1:
      ansible_host: 62.84.125.153
      ip: 10.128.0.14
#      access_ip: 84.201.134.139
    node1:
      ansible_host: 62.84.125.238
      ip: 10.128.0.7
#      access_ip: 84.201.130.228
#    node2:
#      ansible_host: 130.193.37.86
#      ip: 10.128.0.14
#      access_ip: 62.84.118.203
#    node3:
#      ansible_host: 62.84.119.172
#      ip: 10.128.0.11
#      access_ip: 62.84.116.185
#    node4:
#      ansible_host: 62.84.126.227
#     ip: 10.128.0.27
#      access_ip: 84.201.173.4
  children:
    kube_control_plane:
      hosts:
        cp1:
    kube_node:
      hosts:
        node1:
#        node2:
#        node3:
#        node4:
    etcd:
      hosts:
        cp1:
    k8s_cluster:
      children:
        kube_control_plane:
        kube_node:
    calico_rr:
      hosts: {}
